name: testing
on: [push, pull_request]
jobs:
    golangci-lint-check:
        name: golangci-lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go: [1.16.x, 1.17.x]
        steps:
            - uses: actions/checkout@v2

            - name: Run lint
              uses: reviewdog/action-golangci-lint@v2
              with:
                  go_version: ${{ matrix.go }}
        

    go-testing:
        name: go-testing
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go: [1.16.x, 1.17.x]
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-go@v2
              with:
                  go-version: ${{ matrix.go }}

            - name: Install richgo
              run: make install-richgo

            - name: testing
              run: make test

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  flags: unittests
                  fail_ci_if_error: true
